# example values

server:
  port: 8080

indexing-settings:
  sites:
    - url: https://volochek.life/
      name: Волочек
    - url: https://www.skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru/
      name: PlayBack.Ru
    - url: https://dombulgakova.ru/
      name: Дом Булгакова
    - url: https://et-cetera.ru/mobile/
      name: Театр Et Cetera
    - url: https://www.svetlovka.ru/
      name: Светловка
    - url: https://www.bbc.com/news
      name: BBC News


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

      search:
        tooCommonPercent: 1.0


